name: Free RDP with Cloudflare Tunnel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Enable RDP, Set Password, Start Cloudflare Tunnel
      run: |
        # Set RDP login password
        net user runneradmin YourStrongPassword123!

        # Enable RDP access
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        # Download cloudflared
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "C:\cloudflared.exe"

        # Start the tunnel
        Start-Process -NoNewWindow -FilePath "C:\cloudflared.exe" -ArgumentList "tunnel", "--url", "rdp://localhost:3389"

        # Wait a bit and keep the runner alive
        Start-Sleep -Seconds 10
        Write-Host "RDP is ready. Login using runneradmin / YourStrongPassword123!"
        Write-Host "Tunnel URL will appear in the previous step logs."
        ping 127.0.0.1 -n 21600 > nul
