name: RDP Windows Setup

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download & Extract Cloudflared
      run: |
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Start Tunnel
      run: |
        Start-Process -NoNewWindow -FilePath "cloudflared.exe" -ArgumentList "tunnel", "--url", "rdp://localhost:3389"
        Start-Sleep -s 10

    - name: Show Tunnel URL
      run: |
        Invoke-WebRequest -Uri "http://127.0.0.1:4040/api/tunnels" -UseBasicParsing | Out-File tunnel.json
        Get-Content tunnel.json
